# Generated by Django 4.1.2 on 2022-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('lead', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('channels', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(null=True)),
                ('signed_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateField(null=True)),
            ],
        ),
    ]
