# Generated by Django 4.1.2 on 2022-10-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardReports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sale_representative',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
